FROM ubuntu:16.04

RUN apt-get -yq update \
        && apt-get -yq install openssh-server curl \
        && mkdir -m 755 /run/sshd \
        && mkdir -m 700 /root/.ssh

COPY authorized_keys /root/.ssh/authorized_keys

CMD ["/usr/sbin/sshd", "-D"]

