#!/usr/bin/env zsh
set -e

usage() {
    print "./update URL or file path"
}

if [[ -z $1 ]]; then
    usage
    exit 1
fi

# cd to NMK_DIR
cd ${0:A:h}

if [[ -e $1 ]]; then
    cp $1 .
else
    curl -O -J -L $1
fi
BUNDLE_FILE=$(basename $1)

sh uninstall.sh
tar -x -f $BUNDLE_FILE --strip-components=1
rm $BUNDLE_FILE
print "Updated nmk, Top commit is $(cat HEAD)"

