#!/usr/bin/env zsh
set -e

usage() {
    print "./update URL"
}

if [[ -z $1 ]]; then
    usage
    exit 1
fi

# cd to NMK_DIR
cd ${0:A:h}

BUNDLE_URL=$1
BUNDLE_NAME=$(basename $BUNDLE_URL)

wget $BUNDLE_URL
sh uninstall.sh
tar -x -f $BUNDLE_NAME --strip-components=1
rm $BUNDLE_NAME
print "Updated nmk"
print "Top commit is"
cat HEAD

