#!/usr/bin/env zsh
set -e

usage() {
    print "./update URL or FILE"
}

if [[ -z $1 ]]; then
    usage
    exit 1
fi

BUNDLE_NAME=$(basename $1)
if [[ -e $1 ]]; then
    cp $1 $NMK_DIR
else
    curl -o $NMK_DIR/$BUNDLE_NAME -L $1
fi

cd $NMK_DIR
sh uninstall.sh
tar -x -f $BUNDLE_NAME --strip-components=1
rm $BUNDLE_NAME
print "Updated nmk, Top commit is $(cat HEAD)"

