#!/bin/sh
set -ex

export CLOUDSDK_ACTIVE_CONFIG_NAME=nui

for target in amd64 arm64 arm; do
    python3 build.py --strip --target $target --dist "$@"
done

gsutil -m -h "Cache-Control: no-store, no-transform" rsync dist/ gs://nmk.nuimk.com/
