FROM ubuntu:14.04

RUN apt-get -yq update \
    && apt-get -yq install \
        build-essential \
        gcc-arm-linux-gnueabihf \
        binutils \
        curl \
        make \
        zsh \
    && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path \
    && . /root/.cargo/env \
    && rustup target add armv7-unknown-linux-gnueabihf \
    && rm -rf /var/lib/apt/lists/*

COPY cargo-config /root/.cargo/config

ENV DIST_DIR=/workspace
