#!/usr/bin/env zsh

cd ${0:A:h:h}

files=(
    vim/shada/main.shada
    vim/viminfo
    zsh/.zcompdump
    zsh/.zsh_history
)

read -q "confirm?Wipe history? (y/n)"

[[ $confirm != y ]] && exit 0

for file in $files; do
    if [[ -f $file ]]; then
        shred -n 30 -u $file
        print -- "removed ${file:a}"
    fi
done
