FROM alpine

RUN apk --update add coreutils curl git python3 xz

WORKDIR /root

RUN curl -sSL -o /root/build.py https://raw.githubusercontent.com/nui/nmk/master/etc/build.py

ARG ENTRYPOINT=https://storage.googleapis.com/nmk.nuimk.com/nmk-x86_64-unknown-linux-musl.xz

RUN tmp_file=$(mktemp) \
        && curl -sSL $ENTRYPOINT | xz -d > $tmp_file \
        && install $tmp_file /usr/local/bin/nmk

ENTRYPOINT ["python3", "/root/build.py", "--no-upload", "--branch", "master"]

