FROM ubuntu

RUN apt-get -yq update \
    && apt-get -yq install \
        git \
        zsh \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root

RUN git clone https://github.com/nuimk/nmk.git ~/.nmk

ENTRYPOINT ["/root/.nmk/etc/build", "--keep", "--no-upload", "--branch", "master"]

