FROM golang:alpine

RUN apk add --no-cache \
    binutils \
    curl \
    git \
    make

ARG DEP_INSTALL_PATH=/usr/local/go/bin/dep
ARG DEP_VERSION=v0.5.3
# install go dep
RUN curl -sSLo $DEP_INSTALL_PATH \
        https://github.com/golang/dep/releases/download/${DEP_VERSION}/dep-linux-amd64 \
    && chmod 755 $DEP_INSTALL_PATH

COPY nmk.go/ /go/
RUN cd /go \
    && make alpine

