#!/bin/bash

# The reason why this is bash script because sometimes we doesn't have
# permissions to install zsh globally

set -e

# PARSE OPTIONS {{{
if ! _TEMP=$(POSIXLY_CORRECT=true getopt -o '' --long prune-reflog,log -- "$@"); then
    # exit if error
    exit 1
fi

eval set -- "$_TEMP"

# Variables
_PRUNE_REFLOG=false
_LOG=false

while true; do
    case $1 in
        --prune-reflog ) _PRUNE_REFLOG=true; shift ;;
        --log) _LOG=true; shift ;;
        -- ) shift; break ;;
    esac
done
# END PARSE OPTIONS }}}


# find nmk directory, usually ~/.nmk
export NMK_DIR="$(dirname "$(dirname "$(readlink -f -- "$BASH_SOURCE")")")"
_LOGFILE="$NMK_DIR/log/automatic-update.log"


self_update() {
    local timestamp
    timestamp=$(date -u --rfc-3339 seconds)
    cd "$NMK_DIR"
    # delete all tags
    git tag -d $(git tag) >/dev/null 2>&1

    echo "-- $timestamp"
    git remote update --prune && git reset --hard origin/master
    if [[ $_PRUNE_REFLOG == true ]]; then
        git reflog expire --expire=now --all
        git gc --prune=now
        git repack -AdF
    fi
    # checkout submodules
    git submodule update --force --init --recursive
    # update vim plugins
    ./vim/update-plugins
    # remove untracked files
    git clean -f
}

if [[ $_LOG == true ]]; then
    self_update | tee -a $_LOGFILE
else
    self_update
fi
