#!/bin/sh

delete_old_job() {
    local copy="$(crontab -l 2>/dev/null)"

    if [ $? -eq 0 ] && [ -n "$copy" ]; then
        # delete old jobs
        echo "$copy" | grep -v -E '\.nmk/scripts/automatic-update' | crontab
    fi
}

generate_cron_config() {
    # print current configuration if exist
    crontab -l 2>/dev/null || true
    # update twice a day
    cat <<- EOCRON
		0 */12 * * * "\$HOME/.nmk/scripts/automatic-update --prune-reflog --log"
	EOCRON
}

delete_old_job
generate_cron_config | crontab
