#!/bin/bash

append_alias() {
cat << 'EOF'
# nmk alias
if [[ -e ~/.nmk/bin/nmk ]]; then alias nmk='~/.nmk/bin/nmk'; fi
EOF
}

delete_alias() {
    sed -i '/alias nmk=/d' $1
}

RCFILE=~/.bashrc

if [[ -e $RCFILE ]]; then
    delete_alias $RCFILE
    append_alias >> $RCFILE
fi
