#!/bin/bash

append_alias() {
cat << 'EOF'
if [[ -e ~/.nmk/bin/nmk ]]; then alias nmk='~/.nmk/bin/nmk'; fi # just an alias, see ~/.nmk/README.md for more information
EOF
}

delete_alias() {
    sed -i '/alias nmk=/d' $1
}

if grep -q --fixed-strings '. ~/.bash_aliases' ~/.bashrc; then
    alias_file=~/.bash_aliases
    touch $alias_file
else
    alias_file=~/.bashrc
fi

if [[ -e $alias_file ]]; then
    delete_alias $alias_file
    append_alias >> $alias_file
fi
